Repository ucsb-cs156-m23/proj-gauchoride-m23-9am-3, pull requests merged in 2023-08, with the labels that each got.

#34 Setting up Privacy Policy
  frontend/src/App.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/pages/PrivacyPolicy.js
  frontend/src/main/pages/privacy.html
  frontend/src/tests/pages/PrivacyPolicy.test.js
Labels: Ready for review

#35 AW--Updated Frontend of RideRequest
  frontend/src/fixtures/rideFixtures.js
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/main/pages/Ride/RideRequestCreatePage.js
  frontend/src/main/pages/Ride/RideRequestEditPage.js
  frontend/src/tests/components/Ride/RideForm.test.js
  frontend/src/tests/components/Ride/RideTable.test.js
  frontend/src/tests/pages/Ride/RideRequestCreatePage.test.js
  frontend/src/tests/pages/Ride/RideRequestEditPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Ride.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RideControllerTests.java
Labels: Ready for review

#38 AW--implemented the entire backend controller for RiderApplication
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Ride.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/RiderApplication.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/RiderApplicationRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
Labels: Ready for review

#20 ShiftController backend operations and tests, Entity and Repository Implemented
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/ShiftControllerTests.java
Labels: Ready for review

#39 Made Improvements for github to have faster Stryker runs
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
Labels: 5, Ready for review

#31 Implemented Shift Pages (Create, Edit and Index)
  frontend/src/App.js
  frontend/src/fixtures/shiftFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Shift/ShiftCreatePage.js
  frontend/src/main/pages/Shift/ShiftEditPage.js
  frontend/src/main/pages/Shift/ShiftIndexPage.js
  frontend/src/stories/pages/Shift/ShiftCreatePage.stories.js
  frontend/src/stories/pages/Shift/ShiftEditPage.stories.js
  frontend/src/stories/pages/Shift/ShiftIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
  frontend/src/tests/pages/Shift/ShiftEditPage.test.js
  frontend/src/tests/pages/Shift/ShiftIndexPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ApiController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/ShiftControllerTests.java
Labels: 10, MergeCandidate-CI

#30 Add User Cellphone
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/tests/pages/ProfilePage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UserProfileController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
  src/main/java/edu/ucsb/cs156/gauchoride/models/CurrentUser.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/UserProfileControllerTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/models/CurrentUserTests.java
Labels: 10, MergeCandidate-CI

#44 AW--Implemented Index/Create/Edit Page for Rider Application from Member's View
  .github/workflows/34-frontend-main-mutation-testing.yml
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/RiderApplication/RiderApplicationForm.js
  frontend/src/main/pages/RiderApplication/RiderApplicationCreatePage.js
  frontend/src/main/pages/RiderApplication/RiderApplicationEditPageMember.js
  frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageMember.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationCreatePage.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationEditPageMember.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageMember.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
Labels: Ready for review

#45 Rider Application Index Page for Admins & Review Page Placeholder
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageAdmin.js
  frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageMember.js
  frontend/src/main/pages/RiderApplication/RiderApplicationReviewPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageAdmin.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationReviewPage.test.js
Labels: 10, MergeCandidate-CI
